### PR TITLE
cmake based build

### PR DESCRIPTION
**Pull request by jurica**
Hi,

I coincidentally saw the demo of this on Youtube and wanted to try it out. As I'm on macOS I wasn't able to just run the exe and I also wanted to mess around with the parameters, so I needed to build it myself.
As the Makefile wasn't working immediately for me so, I put together the few lines of CMake needed to build it.

I thought it perhaps might be useful for somebody else as well, so I filed this PR.

Regards,
Juri

### CODE REVIEW

**Comment by codemaker4** [comment]
Hello Jurica,

First of all, I appreciate the thought and attention you gave to this somewhat abandoned and old project of mine.
I am not very proficient at C/C++ and am unfamiliar with CMake. The original makefile is indeed made for windows, so making a better cross-platform solution is desirable. However, when I try to use CMake (again, without any good knowledge and experience, I just did `cmake CMakeLists.txt` and then `make` on my Linux machine) it makes quite the clutter of files. I like that this makes it cross platform, but it makes it seem a bit overkill. Is there a way to cut down the clutter, or at least hide it in a folder?

I am not really planning to put much time into this project myself, but I am OK with accepting good pull requests. (see #2) So just another commit that simply hides the cmake files away in a folder (preferably in an industry standard way, because I suspect this project will become a source of education for some) and some quick usage instructions in the README file would be great.

Thank you for your time and a happy new year!

**Comment by jurica** [comment]
Hi,

thanks, happy new year to you as well!

You're right, if you would run cmake on the provided CMakeLists.txt, CMake would generate the build system in the folder you ran it and thus make the clutter of files you're referring to.
But for several reasons it's most common to put the CMakeList.txt into the top level folder of a C++ project and then generate the buildsystem out-of-tree. That's why I added the CMakePresets.json and set "binaryDir" to "../build", so one can run ```cmake --preset=default``` and then ```cmake --build --preset=default``` in order to get an out-of-tree build.
The first command will create a folder called "build" in the parent directory and then generate the buildsystem (in this case using Ninja). The second command would then run the actual build and produce a binary called "raylib-particle-toy" (with .exe suffix on Windows).
Alternatively without leveraging CMake presets one can also generate the buildsystem out-of-tree by simply calling cmake from another folder or by passing the ```-B``` switch.

Putting the build dir into the parent folder is just my common choice for the build location.
But after rethinking I'd suggest the following:
1. change the "binaryDir" to "build" and add that folder to .gitignore
2. add some instructions to the readme how to run cmake properly using the provided files

Let me know if this would suite your expectations. I'd happily adjust the PR.
I really think this little project is a source of education to some extend. At least it was for me as it was a quick possibility to dip into raylib and have a small working codebase I can do some experiments on and understand some basic concepts.

**Comment by codemaker4** [comment]
Yeah, that sounds good. If you would make those changes I will merge the PR.
Thanks again for your time.

**Comment by jurica** [comment]
You're welcome, I also have to say thank you, it was a nice kickstart into raylib!

Please check the PR again. I did the discussed adjustments, if you don't like my wording or miss anything feel free to adjust it to your likings.

**Comment by codemaker4** [comment]
Thanks! I merged this.

**Pull request merged**
